Update App Icon

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -16,7 +16,7 @@ jobs:
     # The type of runner that the job will run on
     runs-on: macos-11
     timeout-minutes: 20
-        
+
     steps:
       - uses: actions/checkout@v2
       - name: Apply Apple certificate and provisioning profile
@@ -49,7 +49,6 @@ jobs:
           mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
           cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/
 
-          
       - name: Update Dependency
         working-directory: ./MVVMExample
         run: |
@@ -58,31 +57,47 @@ jobs:
       - name: Archive File IPA & Upload to TestFlight
         working-directory: ./MVVMExample
         env:
-          EXPORT_SCHEME: 'MVVMExample'
-          EXPORT_DIR: './output'
-          EXPORT_OPTIONS_PLIST_DIR: './config/export-config.plist'
+          EXPORT_SCHEME: "MVVMExample"
+          EXPORT_WORKSPACE: "MVVMExample.xcworkspace"
+          EXPORT_DIR: "./output"
+          EXPORT_PRIVATE_KEYS_DIR: "./private_keys"
+          EXPORT_DIR_IPA: "$EXPORT_DIR/MVVMExample.ipa"
+          EXPORT_ARCHIVE_DIR: "$EXPORT_DIR/MVVMExample.xcarchive"
+          EXPORT_DESTINATION: "generic/platform=iOS"
+          EXPORT_OPTIONS_PLIST_DIR: "./config/export-config.plist"
 
           APP_CONNECT_USER_ID: ${{ secrets.APP_CONNECT_USER_ID }}
           APP_CONNECT_KEY_ID: ${{ secrets.APP_CONNECT_KEY_ID }}
           APP_CONNECT_PRIVATE_KEY: ${{ secrets.APP_CONNECT_PRIVATE_KEY }}
 
         run: |
+          # Remove previous export folder
           rm -rf "$EXPORT_DIR"
+          # Start archive project
+          set -o pipefail && xcodebuild \
+            -workspace "./$EXPORT_WORKSPACE" \
+            -scheme "$EXPORT_SCHEME" \
+            -destination "$EXPORT_DESTINATION" \
+            -archivePath "$EXPORT_ARCHIVE_DIR" \
+            archive;
           
-          set -o pipefail && xcodebuild -workspace "./MVVMExample.xcworkspace" -scheme "$EXPORT_SCHEME" -destination 'generic/platform=iOS' -archivePath "./MVVMExample.xcarchive" archive;
+          # Export IPA
+          xcodebuild -exportArchive \
+            -archivePath "$EXPORT_ARCHIVE_DIR" \
+            -exportPath "$EXPORT_DIR" \
+            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST_DIR" \
+            -allowProvisioningUpdates;
+            
+          rm -rf "$EXPORT_ARCHIVE_DIR"
 
-          xcodebuild -exportArchive -archivePath "./MVVMExample.xcarchive" -exportPath "$EXPORT_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST_DIR" -allowProvisioningUpdates;
-          
-          rm -rf "./MVVMExample.xcarchive"
-
-          if [ ! -f "$EXPORT_DIR/MVVMExample.ipa" ]
+          if [ ! -f "$EXPORT_DIR_IPA" ]
           then
-            echo "MVVMExample.ipa not found!"
+            echo "IPA not found!"
           else
-            mkdir "./private_keys"
-            echo "$APP_CONNECT_PRIVATE_KEY" >> "./private_keys/AuthKey_${APP_CONNECT_KEY_ID}.p8"
+            mkdir "$EXPORT_PRIVATE_KEYS_DIR"
+            echo "$APP_CONNECT_PRIVATE_KEY" >> "$EXPORT_PRIVATE_KEYS_DIR/AuthKey_${APP_CONNECT_KEY_ID}.p8"
             echo "Start upload ipa to TestFlight!"
-            xcrun altool --upload-app --type ios --file "$EXPORT_DIR/MVVMExample.ipa" --apiKey $APP_CONNECT_KEY_ID  --apiIssuer $APP_CONNECT_USER_ID
+            xcrun altool --upload-app --type ios --file $EXPORT_DIR_IPA --apiKey $APP_CONNECT_KEY_ID  --apiIssuer $APP_CONNECT_USER_ID
           fi
           
       - name: Clean up keychain and provisioning profile
