Update work flow

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -54,44 +54,44 @@ jobs:
           security list-keychain -d user -s $KEYCHAIN_PATH
 
           # apply provisioning profile
-          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+          mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
+          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/
           cd ~/Library/MobileDevice/Provisioning\ Profiles
           ls
           echo "****** LIST CERTIFICATE******"
           security find-identity -p codesigning -v
           
-      - name: Update Dependency
-        working-directory: ./MVVMExample
-        run: |
-          pod install
+#      - name: Update Dependency
+#        working-directory: ./MVVMExample
+#        run: |
+#          pod install
           
-      - name: Archive File IPA & Upload to TestFlight
-        working-directory: ./MVVMExample
-        env:
-          EXPORT_SCHEME: 'MVVMExample'
-          EXPORT_DIR: './output'
-          EXPORT_OPTIONS_PLIST_DIR: './config/export-config.plist'
-          
-          APP_CONNECT_USER_ID: ${{ secrets.APP_CONNECT_USER_ID }}
-          APP_CONNECT_KEY_ID: ${{ secrets.APP_CONNECT_KEY_ID }}
-          APP_CONNECT_PRIVATE_KEY: ${{ secrets.APP_CONNECT_PRIVATE_KEY }}
-          
-        run: |
-          rm -rf "$EXPORT_DIR"
-          set -o pipefail && xcodebuild -workspace "./MVVMExample.xcworkspace" -scheme "$EXPORT_SCHEME" -destination 'generic/platform=iOS' -archivePath "./MVVMExample.xcarchive" archive;
-        
-                    
-          arch -x86_64 xcodebuild -exportArchive -archivePath "./MVVMExample.xcarchive" -exportPath "$EXPORT_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST_DIR";
-          rm -rf "./MVVMExample.xcarchive"
-          
-          if [ ! -f "$EXPORT_DIR/MVVMExample.ipa" ]
-          then
-            echo "MVVMExample.ipa not found!"
-          else
-            mkdir "./private_keys"
-            echo "$APP_CONNECT_PRIVATE_KEY" >> "./private_keys/AuthKey_${APP_CONNECT_KEY_ID}.p8"
-            echo "Start upload ipa to TestFlight!"
-            xcrun altool --upload-app -f $EXPORT_DIR -t ios --apiKey $APP_CONNECT_KEY_ID  --apiIssuer $APP_CONNECT_USER_ID
-          fi
+#      - name: Archive File IPA & Upload to TestFlight
+#        working-directory: ./MVVMExample
+#        env:
+#          EXPORT_SCHEME: 'MVVMExample'
+#          EXPORT_DIR: './output'
+#          EXPORT_OPTIONS_PLIST_DIR: './config/export-config.plist'
+#
+#          APP_CONNECT_USER_ID: ${{ secrets.APP_CONNECT_USER_ID }}
+#          APP_CONNECT_KEY_ID: ${{ secrets.APP_CONNECT_KEY_ID }}
+#          APP_CONNECT_PRIVATE_KEY: ${{ secrets.APP_CONNECT_PRIVATE_KEY }}
+#
+#        run: |
+#          rm -rf "$EXPORT_DIR"
+#          set -o pipefail && xcodebuild -workspace "./MVVMExample.xcworkspace" -scheme "$EXPORT_SCHEME" -destination 'generic/platform=iOS' -archivePath "./MVVMExample.xcarchive" archive;
+#
+#
+#          arch -x86_64 xcodebuild -exportArchive -archivePath "./MVVMExample.xcarchive" -exportPath "$EXPORT_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST_DIR";
+#          rm -rf "./MVVMExample.xcarchive"
+#
+#          if [ ! -f "$EXPORT_DIR/MVVMExample.ipa" ]
+#          then
+#            echo "MVVMExample.ipa not found!"
+#          else
+#            mkdir "./private_keys"
+#            echo "$APP_CONNECT_PRIVATE_KEY" >> "./private_keys/AuthKey_${APP_CONNECT_KEY_ID}.p8"
+#            echo "Start upload ipa to TestFlight!"
+#            xcrun altool --upload-app -f $EXPORT_DIR -t ios --apiKey $APP_CONNECT_KEY_ID  --apiIssuer $APP_CONNECT_USER_ID
+#          fi
   
