Update work flow

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -14,18 +14,10 @@ jobs:
   # This workflow contains a single job called "build"
   build:
     # The type of runner that the job will run on
-    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [macos-11]
-        swift: ["5.2"]
     runs-on: macos-latest
     timeout-minutes: 20
         
     steps:
-      - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
-        with:
-          swift-version: ${{ matrix.swift }}
       - uses: actions/checkout@v2
       - name: Apply Apple certificate and provisioning profile
         env:
@@ -55,40 +47,40 @@ jobs:
 
           # apply provisioning profile
           mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
-          echo "${PP_PATH}"
           cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/
+
           
-#      - name: Update Dependency
-#        working-directory: ./MVVMExample
-#        run: |
-#          pod install
+      - name: Update Dependency
+        working-directory: ./MVVMExample
+        run: |
+          pod install
           
-#      - name: Archive File IPA & Upload to TestFlight
-#        working-directory: ./MVVMExample
-#        env:
-#          EXPORT_SCHEME: 'MVVMExample'
-#          EXPORT_DIR: './output'
-#          EXPORT_OPTIONS_PLIST_DIR: './config/export-config.plist'
-#
-#          APP_CONNECT_USER_ID: ${{ secrets.APP_CONNECT_USER_ID }}
-#          APP_CONNECT_KEY_ID: ${{ secrets.APP_CONNECT_KEY_ID }}
-#          APP_CONNECT_PRIVATE_KEY: ${{ secrets.APP_CONNECT_PRIVATE_KEY }}
-#
-#        run: |
-#          rm -rf "$EXPORT_DIR"
-#          set -o pipefail && xcodebuild -workspace "./MVVMExample.xcworkspace" -scheme "$EXPORT_SCHEME" -destination 'generic/platform=iOS' -archivePath "./MVVMExample.xcarchive" archive;
-#
-#
-#          arch -x86_64 xcodebuild -exportArchive -archivePath "./MVVMExample.xcarchive" -exportPath "$EXPORT_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST_DIR";
-#          rm -rf "./MVVMExample.xcarchive"
-#
-#          if [ ! -f "$EXPORT_DIR/MVVMExample.ipa" ]
-#          then
-#            echo "MVVMExample.ipa not found!"
-#          else
-#            mkdir "./private_keys"
-#            echo "$APP_CONNECT_PRIVATE_KEY" >> "./private_keys/AuthKey_${APP_CONNECT_KEY_ID}.p8"
-#            echo "Start upload ipa to TestFlight!"
-#            xcrun altool --upload-app -f $EXPORT_DIR -t ios --apiKey $APP_CONNECT_KEY_ID  --apiIssuer $APP_CONNECT_USER_ID
-#          fi
+      - name: Archive File IPA & Upload to TestFlight
+        working-directory: ./MVVMExample
+        env:
+          EXPORT_SCHEME: 'MVVMExample'
+          EXPORT_DIR: './output'
+          EXPORT_OPTIONS_PLIST_DIR: './config/export-config.plist'
+
+          APP_CONNECT_USER_ID: ${{ secrets.APP_CONNECT_USER_ID }}
+          APP_CONNECT_KEY_ID: ${{ secrets.APP_CONNECT_KEY_ID }}
+          APP_CONNECT_PRIVATE_KEY: ${{ secrets.APP_CONNECT_PRIVATE_KEY }}
+
+        run: |
+          rm -rf "$EXPORT_DIR"
+          set -o pipefail && xcodebuild -workspace "./MVVMExample.xcworkspace" -scheme "$EXPORT_SCHEME" -destination 'generic/platform=iOS' -archivePath "./MVVMExample.xcarchive" archive;
+
+
+          arch -x86_64 xcodebuild -exportArchive -archivePath "./MVVMExample.xcarchive" -exportPath "$EXPORT_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST_DIR";
+          rm -rf "./MVVMExample.xcarchive"
+
+          if [ ! -f "$EXPORT_DIR/MVVMExample.ipa" ]
+          then
+            echo "MVVMExample.ipa not found!"
+          else
+            mkdir "./private_keys"
+            echo "$APP_CONNECT_PRIVATE_KEY" >> "./private_keys/AuthKey_${APP_CONNECT_KEY_ID}.p8"
+            echo "Start upload ipa to TestFlight!"
+            xcrun altool --upload-app -f $EXPORT_DIR -t ios --apiKey $APP_CONNECT_KEY_ID  --apiIssuer $APP_CONNECT_USER_ID
+          fi
   
